services:
    anime_db.shikimori.search:
        class: AnimeDb\Bundle\ShikimoriFillerBundle\Service\Search
        arguments: [ @anime_db.shikimori.browser, @anime_db.shikimori.search_form, %locale% ]
        tags:
            - { name: anime_db.search }
        calls:
            - [setRouter, ['@router']]
            - [setFiller, ['@anime_db.shikimori.filler']]

    anime_db.shikimori.filler:
        class: AnimeDb\Bundle\ShikimoriFillerBundle\Service\Filler
        arguments: [ @anime_db.shikimori.browser, @doctrine, @anime_db.downloader, %locale% ]
        tags:
            - { name: anime_db.filler }
        calls:
            - [setRouter, ['@router']]

    anime_db.shikimori.refiller:
        class: AnimeDb\Bundle\ShikimoriFillerBundle\Service\Refiller
        arguments: [ @anime_db.shikimori.browser, @anime_db.shikimori.filler, @anime_db.shikimori.search ]
        tags:
            - { name: anime_db.refiller }

    anime_db.shikimori.search_form:
        class: AnimeDb\Bundle\ShikimoriFillerBundle\Form\Type\Search
        arguments: [ @anime_db.shikimori.browser, %locale% ]

    anime_db.shikimori.listener.refiller:
        class: AnimeDb\Bundle\ShikimoriFillerBundle\Event\Listener\Refiller
        arguments: [ @event_dispatcher, @anime_db.shikimori.refiller, @anime_db.shikimori.filler ]
        tags:
            - { name: kernel.event_listener, event: anime_db.storage.add_new_item, method: onAddNewItem }
